### ISSUE TITLE
snippet_sizes not support in Client.search

### ISSUE THREAD

**Issue by ibroomcorn** [RediSearch/redisearch-py#26]
https://github.com/RedisLabs/redisearch-py/blob/b8c7c66b1d5b9125271aa77db19030d2dcee44f2/redisearch/client.py#L306

**Comment by AvitalFineRedis** [comment]
I'm closing this issue because this parameter was removed from the description (as you can see [here](https://github.com/RediSearch/redisearch-py/commit/42e81fa49e1062c6a96e08784c92e4029ff41a9e#diff-f18807ed6f8f6832af0c1[…]9216159259db5e48e463b8407ee)). Probably the requirements have been changed...
