### ISSUE TITLE
'load_document' can load deleted  data

### ISSUE THREAD

**Issue by new-commer** [RediSearch/redisearch-py#71]
I delete the data manually via `FT.DEL`.  And i did the check by `ft.get` make sure it had been deleted.

Then i run my python code `load_document`, it can load the deleted data.

Any suggestions ?

**Comment by gkorland** [comment]
How did you add the the doc at the first place?

**Comment by dipinarora9** [comment]
Hey @new-commer ,
When you use the FT.DEL command it just deletes the index of the document and not the actual document.
That's why FT.GET command didn't return your document because its index has been deleted.
To delete the actual document along with its index you have to pass the argument `DD` after the document id in FT.DEL command.

Also, #69 adds the support for DD argument in redisearch-py.

**Comment by new-commer** [comment]
Got it. Thank you.
